### ISSUE TITLE
Les fonctionnalités attendues par les utilisateurs sont listées

### ISSUE THREAD

**Issue by liZe** [Kozea/babyte#1]

**Comment by JordanKozea** [comment]
Listes des fonctionnalités attendues par les utilisateurs : 
- **Planning des grosses rencontres**
- **Statistiques de la dernière semaine par individu (%Victoire/Défaite, But(s) marqué(s)**  
- **Principe de la ceinture attribuer à la première personne enchaînant un nombre de victoires suffisant. Ce dernier pouvant la perdre à la première défaite.**
- **Instaurer un système de pari : doubler les points d'une rencontre suite à un pré-accord de TOUS les participants au match**
- **Classement en fonction des règles : classement différent selon que l'on applique les règles dites "Bistrot" ou "Championnat"**
- **En fonction du classement, organiser des coupes en fin de période avec des équipes plus ou moins équilibrés**
-   **les tops des binômes, le top individuel, afficher les règles appliquées**
- **Equipe aléatoire**
- **1Vs1 ou 2Vs2**
- calendrier des futurs matchs
- handicap : lié à l'âge ou au niveau du jouer (Débutant-Moyen-Expert)
- le plus mauvais but
- Instaurer un système de gages (à développer)
