### ISSUE TITLE
La maquette de l'application est créée

### ISSUE THREAD

**Issue by JordanKozea** [Kozea/babyte#7]

**Comment by hugo-perier** [comment]
![babyte - classement](https://cloud.githubusercontent.com/assets/20473458/23858405/9251de2e-0800-11e7-93c5-84b39aa4d7c5.png)
![babyte - historique](https://cloud.githubusercontent.com/assets/20473458/23858406/92586e4c-0800-11e7-87da-92203a03d57c.png)

**Comment by hugo-perier** [comment]
@annabellou @JordanKozea @Le-Stagiaire : Vous en pensez quoi ?

**Comment by annabellou** [comment]
J'aime bien le choix des couleurs, c'est clair et minimaliste, on sait tout de suite où sont les différentes parties.

Le choix des font, pourquoi pas, au premier abord je ne suis pas ultra fan mais ça change donc c'est bien ! il faudra voir si ça reste assez lisible une fois sur le web.

Par contre, je n'ai pas bien compris un truc : on rentre les personnes des différentes équipes, mais comment on fait pour le score ? on peut cliquer dans le cercle où il y le chiffre ?

**Comment by hugo-perier** [comment]
Ouais le rond c'est un champ input donc tu cliques dedans et tu rentres le score
